export const INSTITUTION_TYPES = {
  PUBLIC: 'PUBLIC',
  MUSEUM: 'MUSEUM',
  SCIENCE_CENTER: 'SCIENCE_CENTER',
  FACTORY: 'FACTORY',
  BROADCASTING: 'BROADCASTING',
  OTHER: 'OTHER',
} as const;

export const EXPERIENCE_CATEGORIES = {
  DOCENT: 'DOCENT',
  WORKSHOP: 'WORKSHOP',
  FACTORY_TOUR: 'FACTORY_TOUR',
  EXHIBITION: 'EXHIBITION',
  PERFORMANCE: 'PERFORMANCE',
  EDUCATIONAL: 'EDUCATIONAL',
  OUTDOOR: 'OUTDOOR',
  SPECIAL_EVENT: 'SPECIAL_EVENT',
  OTHER: 'OTHER',
} as const;

export const BOOKING_METHODS = {
  FIRST_COME: 'FIRST_COME',
  LOTTERY: 'LOTTERY',
  ALWAYS_AVAILABLE: 'ALWAYS_AVAILABLE',
} as const;

export const EXPERIENCE_RUN_STATUS = {
  UNKNOWN: 'UNKNOWN',
  OPENING_SOON: 'OPENING_SOON',
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
} as const;
